### ISSUE TITLE
Wrong optimistic matching of route with undesired pattern

### ISSUE THREAD

**Issue by staltz** [staltz/switch-path#1]
``` js
const routes = {
  '/': h('h1', 'Hello, world'),
  '/authors': h('h1', 'Authors'),
  '/books': h('h1', 'Books'),
  '/books/:id': id => h('h1', `BookId: ${id}`)
}
```

When I navigated to `/home/33/books/10` I was given `/books/33`

https://github.com/cyclejs/cycle-core/issues/159#issuecomment-143846923

**Comment by TylorS** [comment]
Shouldn't this still be open?

**Comment by staltz** [comment]
I don't why and if I closed this.

**Comment by TylorS** [comment]
Probably from the original pull request referenced 'fixing' this. Still strange behaviour

**Comment by Frikki** [comment]
@staltz You closed it by referencing it in the commit message "Fix #1".

**Comment by staltz** [comment]
Wow

**Comment by TylorS** [comment]
I'm wondering how we'd like to handle this problem now anyways. 
Should we ever return `null/undefined` when a path is entirely unmatchable?
Or maybe we should have the option to match a 'not found' route value? 

``` js
const routes = {
  '/': 123,
  '*':  'Not Found' // Possible way to declare this
}
```

Which would lead to another question on how we would handle server side errors?

**Comment by staltz** [comment]
I like the 'not found' better, but in case that one is not specified, then null.

**Comment by TylorS** [comment]
So look for a 'not found' route, if it exists return that, but if it doesnt return null?

**Comment by staltz** [comment]
yeah

**Comment by TylorS** [comment]
If this 'not found' route _is_ defined. What should the 'path' be? The sourcePath, matchedPath, 'not found', or something else?

**Comment by TylorS** [comment]
I was thinking it should return `sourcePath`

**Comment by staltz** [comment]
Yes

**Comment by TylorS** [comment]
@staltz If you want to check out the possible fix here at https://github.com/TylorS/switch-path/tree/testing
If you like how it's solved I'll update the README and submit a pull request

**Comment by staltz** [comment]
Based on the tests and most of the implementation, it looks good to submit a PR.

**Comment by TylorS** [comment]
I decided to add another test, 

``` js
it('should match an incomplete pattern on multipart path', () => {
    const {path, value} = switchPath('/home/foo/bar', {
      '/home': {
        '/': 123,
        '/foo': 456
      }
    });
    expect(path).to.be.equal('/home/foo');
    expect(value).to.be.equal(456);
  });
```

And this fails, I'm going to try to fix this first

**Comment by staltz** [comment]
Good catch.

**Comment by TylorS** [comment]
As a side note, I've really enjoyed trying to abide by your eslint configuration. It really makes me think about what I'm doing :+1:

**Comment by staltz** [comment]
It's a rather exotic eslint config. For instance, with the backticks. It's not a definitive style, I'm experimenting, but so far I like it.

**Comment by TylorS** [comment]
I like the backticks, It still doesn't come natural to me, but it would definitely be useful say you want to add interpolation in there, no changes needed.

**Comment by staltz** [comment]
It's also makes all strings uniform

**Comment by staltz** [comment]
Kind of like const invading everywhere, there's backtick invading as well

**Comment by TylorS** [comment]
I personally prefer the const keyword, I use them by default, if your config enforces it I haven't even noticed lol

**Comment by TylorS** [comment]
Do we think we're in a good enough state to close this?

**Comment by staltz** [comment]
I think so
