### ISSUE TITLE
How important is the optimistic matching feature?

### ISSUE THREAD

**Issue by SteveALee** [staltz/switch-path#20]
The optimistic matching case is the only case when the return path is NOT the same as the input path.

```
const {path, value} = switchPath('/home/foo', {
  '/bar': 123,
  '/home': 456,
});
// path is `/home`
// value is 456
```

This means we have to use the returned path not th imput path. 

Would this feature be missed?

**Comment by TylorS** [comment]
It was a really important design feature when we were getting started.
I actually have a PR to allow for opting out of partial matching https://github.com/staltz/switch-path/pull/17

using a `/$` syntax it will only match the exact route or not at all

**Comment by SteveALee** [comment]
Sounds usable.
