### ISSUE TITLE
Export interfaces more betterer

### ISSUE THREAD

**Issue by mightyiam** [staltz/switch-path#28]
```ts
import switchPath from 'switch-path'
import { RouteDefinitions } from 'switch-path/lib/es2015/types'
```

Is a little bit not more fun than:

```ts
import switchPath, { RouteDefinitions } from 'switch-path'
```

And also might break perhaps, in a non-MAJOR release.

**Comment by mightyiam** [comment]
https://www.npmjs.com/package/pick-path

**Comment by staltz** [comment]
Thanks @mightyiam for forking and publishing a package independently. I honestly think that's the right thing to do, as I clearly have little time to maintain switch-path.

**Comment by mightyiam** [comment]
Sure thing, @staltz. I hope it will serve some users.
